#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

data = json.load(sys.stdin)

host = data["host"]
h2hs = data.get("http2https", True)

# Route the public host name to the Odoo web container inside the pod
set_route_data = {
    "instance": os.environ["MODULE_ID"],
    "url": "http://127.0.0.1:" + os.environ["TCP_PORT"],
    "host": host,
    "http2https": h2hs,
    "lets_encrypt_check": True,
    "lets_encrypt_cleanup": True,
}
if "lets_encrypt" in data:
    set_route_data["lets_encrypt"] = data["lets_encrypt"]

agent.set_route(set_route_data)
