#!/bin/bash

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

runagent render-config || true
systemctl --user daemon-reload
systemctl --user try-restart odoo.service odoo-db.service odoo-app.service
